name: lando-d9
recipe: drupal9
compose:
  - docker-compose.network-mtu.yml
config:
  webroot: .
services:
  appserver:
    ssl: false
    build:
      - composer install --quiet

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
